spring:
  application:
    name: fsp-java-project
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://47.93.188.95:3306/fsp-java-project?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: fsp-java-project
    password: eKj4NKwpC4aCfiTY
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
  data:
    redis:
      host: 47.93.188.95
      port: 6379
      database: 0
      timeout: 10s
      password: jhkdjhkjdhsIUTYURTU_GaCYcK
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: 47.93.188.95
    port: 5672
    username: rabbitmq
    password: rabbitmq
  elasticsearch:
    uris: http://127.0.0.1:9200
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 7200000
      refresh-token:
        expiration: 14400000
